// examples/react/src/Toolbar.tsx
import type { SymbolInfo, ResolutionInfo } from '@ohlcv-examples/shared';
import type { ThemeMode } from '@ohlcv/core';

export interface ToolbarProps {
  symbols: readonly SymbolInfo[];
  resolutions: readonly ResolutionInfo[];
  symbolId: string;
  resolutionId: string;
  theme: ThemeMode;
  live: boolean;
  status: string;
  onSymbolChange: (id: string) => void;
  onResolutionChange: (id: string) => void;
  onThemeToggle: () => void;
  onLiveToggle: () => void;
}

export function Toolbar(props: ToolbarProps) {
  return (
    <header className="toolbar">
      <label>Symbol</label>
      <select value={props.symbolId} onChange={(e) => props.onSymbolChange(e.target.value)}>
        {props.symbols.map((s) => (
          <option key={s.id} value={s.id}>
            {s.label}
          </option>
        ))}
      </select>

      <label>Resolution</label>
      <select value={props.resolutionId} onChange={(e) => props.onResolutionChange(e.target.value)}>
        {props.resolutions.map((r) => (
          <option key={r.id} value={r.id}>
            {r.id}
          </option>
        ))}
      </select>

      <button onClick={props.onThemeToggle}>
        {props.theme === 'dark' ? '🌙 Dark' : '☀ Light'}
      </button>

      <button className={props.live ? 'active' : ''} onClick={props.onLiveToggle}>
        {props.live ? '■ Stop' : '▶ Live'}
      </button>

      <span className="spacer" />
      <span className="status">{props.status}</span>
    </header>
  );
}

// examples/vue/src/Toolbar.vue
<script setup lang="ts">
import type { SymbolInfo, ResolutionInfo } from '@ohlcv-examples/shared';
import type { ThemeMode } from '@ohlcv/core';

defineProps<{
  symbols: readonly SymbolInfo[];
  resolutions: readonly ResolutionInfo[];
  symbolId: string;
  resolutionId: string;
  theme: ThemeMode;
  live: boolean;
  status: string;
}>();

defineEmits<{
  (e: 'update:symbolId', value: string): void;
  (e: 'update:resolutionId', value: string): void;
  (e: 'toggleTheme'): void;
  (e: 'toggleLive'): void;
}>();
</script>

<template>
  <header class="toolbar">
    <label>Symbol</label>
    <select
      :value="symbolId"
      @change="$emit('update:symbolId', ($event.target as HTMLSelectElement).value)"
    >
      <option v-for="s in symbols" :key="s.id" :value="s.id">{{ s.label }}</option>
    </select>

    <label>Resolution</label>
    <select
      :value="resolutionId"
      @change="$emit('update:resolutionId', ($event.target as HTMLSelectElement).value)"
    >
      <option v-for="r in resolutions" :key="r.id" :value="r.id">{{ r.id }}</option>
    </select>

    <button @click="$emit('toggleTheme')">
      {{ theme === 'dark' ? '🌙 Dark' : '☀ Light' }}
    </button>

    <button :class="{ active: live }" @click="$emit('toggleLive')">
      {{ live ? '■ Stop' : '▶ Live' }}
    </button>

    <span class="spacer" />
    <span class="status">{{ status }}</span>
  </header>
</template>
